### ISSUE TITLE
Java WebApplet not working on site "https://www.proceedo.net/applet.htm"

### ISSUE THREAD

**Issue by janparttimaa** [leaningtech/cheerpj-appletrunner#37]
The site [https://www.proceedo.net/applet.htm](https://www.proceedo.net/applet.htm) use Java WebApplet which will run on Internet Explorer if user has been installed Oracle Java SE 8. However using CheerpJ Applet Runner on Google Chrome don't run the site's WebApplet even if I'm pressing "Run applets" on the CheerpJ Applet Runner extension menu.

**Comment by alexp-sssup** [comment]
We have identified the bug and it will be fixed soon.

**Comment by alexp-sssup** [comment]
This problem is fixed with CheerpJ Applet Runner version 8.4, please make sure to update the extension before trying again.

Please note that this applet is very big and at the limit of what our free CheerpJ Applet Runner extension can support. This applet would be better suited for conversion using our full CheerpJ compiler and we are currently trying to contact the applet vendor to check their interest.
