### ISSUE TITLE
Applet runner is not working on my website

### ISSUE THREAD

**Issue by sergeypayu** [leaningtech/cheerpj-appletrunner#4]
In console it throws java.lang.ClassNotFoundException

URL: https://taxer.ua/uk/applet

**Comment by alexp-sssup** [comment]
There is a minor issue with parsing the applet tag, we will fix it soon.

By the way, CheerpJ Applet Runner is a tool designed to run small scale, non commercial applets on a best effort basis. Since this applet appear to be commercial we recommend getting in touch with us at sales@leaningtech.com. By using a commercial version of CheerpJ you will be able to pre-compile the applet to JS for much better performance. We also provide porting service to help you in the process and make sure everything is working correctly.

**Comment by sergeypayu** [comment]
Thanks for your quick response. I'm in touch with Stefano De Rossi about commercial use. But since I can't even run our applet he asked me to make a bug report here. If it's a minor issue, when and how I can get an update?

**Comment by alexp-sssup** [comment]
The applet is now detected correctly, but it fail with an NPE. I can see the same behaviour when executing it with native Java, is it still supposed to work?

**Comment by sergeypayu** [comment]
We don't use applet tag anymore and don't plan to use it in the future. What we are trying to achieve is to make a cheerpj wrapper around our library and then rewrite the UI part from scratch in pure JS.

**Comment by alexp-sssup** [comment]
Ok, closing this bug. Get in touch if you need support on this project.
