### ISSUE TITLE
This extension breaks interactive features on https://web.archive.org/

### ISSUE THREAD

**Issue by stevennyman** [leaningtech/cheerpj-appletrunner#42]
For some reason, visiting https://web.archive.org/ with this extension enabled breaks the interactive features of the website (for example: searching doesn't work, the screenshot crawl is missing, etc.). This issue only occurs when accessing the website over HTTPS, and only when the CheerpJ Applet Runner Chrome extension is enabled. My browser is Microsoft Edge (Chromium-based) 87.0.664.75.

Thanks!

**Comment by alexp-sssup** [comment]
I cannot reproduce any of the behaviours you listed. One thing to note is that Edge is not currently supported, it _should_ be the same as Chrome, but it has never been tested so we cannot guarantee that it works. Please try again with Google Chrome.

Please note that using Java applets from the Wayback Machine are, in general, also unsupported, since the site add various CSP headers which do not work well with our runtime generated JavaScript code.

**Comment by stevennyman** [comment]
Hmm... I tried creating a new browser profile in Edge and installing the same extensions I had on my old profile but I was unable to reproduce the issue. It seems to happen only on my existing profile... I'm not sure why that would happen. Perhaps something was corrupted in my old profile? Since I can just leave the extension disabled, I'll close this issue in a few days if no other solutions are known. Thanks!
