### ISSUE TITLE
Applet version doesn't match expected version on mVISTA browser

### ISSUE THREAD

**Issue by Ofifoni** [leaningtech/cheerpj-appletrunner#49]
Hi,

I'm trying to open the mVISTA browser on this website:
https://pipeline.lbl.gov/cgi-bin/gateway2?bg=mm10&selector=vista

And I get the following message: "Applet version doesn't match expected version"
What should I do?

Thanks!

![Untitled](https://user-images.githubusercontent.com/89386464/130425979-e7b11734-ebfc-4749-94bb-cc1a99735ea2.png)

**Comment by alexp-sssup** [comment]
This website triggers HTTPS "Mixed-content" exceptions due to misconfiguration on the server side. This is not something that we can avoid at the CheerpJ level.

You can try to work around the problem by allowing "Insecure content" from Chrome's Site-Setting for this specific site.

![image](https://user-images.githubusercontent.com/191061/130576190-b08034ff-b3b9-44bb-bb96-299c5c086651.png)
