### ISSUE TITLE
Fails on Circuit

### ISSUE THREAD

**Issue by johnyradio** [leaningtech/cheerpj-appletrunner#5]
Just letting you know so you can improve your extension.

Java version:
http://www.falstad.com/circuit-java/

Java files:
http://www.falstad.com/circuit-java/circuit.zip

JS version:
http://www.falstad.com/circuit

HTML5 version:
http://lushprojects.com/circuitjs

 Thx

**Comment by alexp-sssup** [comment]
Your applet should work now, please clear up the cache and try again. Please note that a better level of performance can be achieved by using the CheerpJ tool to compile the JAR ahead of time. CheerpJ is free to use for non-commercial purposes and you can download it here: http://cheerpj.leaningtech.com/cheerpj/download/noncommercial/index.html

Documentation on how to convert a JAR ahead-of-time: https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#converting-an-applet.

If the Applet runner works for you we would really appreciate a 5-star review on the extension page: https://chrome.google.com/webstore/detail/cheerpj-applet-runner-bet/bbmolahhldcbngedljfadjlognfaaein

**Comment by johnyradio** [comment]
Thx! Will test soon.

**Comment by johnyradio** [comment]
Hello

 

It didn’t seem to work. 

Problem: Your badge showed gray when I loaded page, even tho’ page has applet. 

Then I clicked your “Run applets” button, and got your progress spinner. 

Problem: Was still spinning after 10 minutes. 

 

Maybe another extension is conflicting?

Here are my extensions:

 

Generated: Sat, 06 Jan 2018 20:20:46 GMT

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

 

Extensions: 24

- Lazy Tabs: https://chrome.google.com/webstore/detail/aabgbgciohhaogajcnacpgilhmacdahc

- ShowPassword: https://chrome.google.com/webstore/detail/bbiclfnbhommljbjcoelobnnnibemabl

- CheerpJ Applet Runner Beta: https://chrome.google.com/webstore/detail/bbmolahhldcbngedljfadjlognfaaein

- appear.in screen sharing: https://chrome.google.com/webstore/detail/bodncoafpihbhpfljcaofnebjkaiaiga

- Share Extensions: https://chrome.google.com/webstore/detail/chdafcbnfkfenoeejpaeenpdamhmalhe

- uBlock Origin: https://chrome.google.com/webstore/detail/cjpalhdlnbpafiamejdnhcphjbkeiagm

- CSS and Javascript Injection: https://chrome.google.com/webstore/detail/ckddknfdmcemedlmmebildepcmneakaa

- Tidy Bookmarks Tree Lite: https://chrome.google.com/webstore/detail/cojofepigcheogdcgockpcaijonnehec

- Undirect: https://chrome.google.com/webstore/detail/dohbiijnjeiejifbgfdhfknogknkglio

- YouTube Auto HD + FPS: https://chrome.google.com/webstore/detail/fcphghnknhkimeagdglkljinmpbagone

- AnnoTabe: https://chrome.google.com/webstore/detail/fdhebnledngmjdkhgamneiapbmjeigee

- Eye Protector: https://chrome.google.com/webstore/detail/fgadnbmmolnmbkbklpaojbogcopipopl

- Stop Autoplay for Youtube™: https://chrome.google.com/webstore/detail/figkapeodjhdgnpiamleongcmecfjccb

- Video Speed: https://chrome.google.com/webstore/detail/fnjmlegmhldjolpmcfjhooibnchlafgg

- Tab Finder - by floverdevel: https://chrome.google.com/webstore/detail/hfnickpljocfadhinpemeekdeebaenlo

- Speed-Up Browsing: https://chrome.google.com/webstore/detail/hkhnldpdljhiooeallkmlajnogjghdfb

- Tab Extract: https://chrome.google.com/webstore/detail/iphchnegaodmijmkdlbhbanjhfphhikp

- Disable Extensions Temporarily: https://chrome.google.com/webstore/detail/lcfdefmogcogicollfebhgjiiakbjdje

- Zoom Tab: https://chrome.google.com/webstore/detail/legekacjhcjbkhjnggkbbibckddakkaa

- Audio EQ: https://chrome.google.com/webstore/detail/lfafdlnjaliaghpjdajmlcnnblkgcefh

- Grabilla Screenshot: https://chrome.google.com/webstore/detail/mlkejhoeobiibeeeahncjhhonbholbje

- Personal Blocklist (by Google): https://chrome.google.com/webstore/detail/nolijncfnkgaikbjbdaogikpmpbdcdef

- 1-Click Extension Manager: https://chrome.google.com/webstore/detail/ohajmcdpjokbdoihfhkpbmlmknejmoec

- Web Cache Viewer: https://chrome.google.com/webstore/detail/pbkloffickinnlnmefmjmjbacohecpbd

 

Disabled Extensions: 6

- Move tabs between windows: https://chrome.google.com/webstore/detail/dcgkknngicjdagcjljfbhgdimlfhafag

- Google Docs Offline: https://chrome.google.com/webstore/detail/ghbmnnjooekpmoecnnnilnnbdlolhkhi

- BF - Boost Facebook: https://chrome.google.com/webstore/detail/jaopmidjghipjkgdkhnielilaoodeefj

- Disable autoplay on youtube: https://chrome.google.com/webstore/detail/mhnjhaekhlafoabhhpakebdpemkddcjd

- Smart Ads Finder: https://chrome.google.com/webstore/detail/oojeieppkffpbnmlpipfbblophebaplg

- Data Saver: https://chrome.google.com/webstore/detail/pfmgfdlgomnbgkofeojodiodmgpgmkac

 

Apps: 2

- Codebender App: https://chrome.google.com/webstore/detail/magknjdfniglanojbpadmpjlglepnlko

- 3D STL, OBJ Viewer with Drive: https://chrome.google.com/webstore/detail/pjbghnibbgbmpokpcfoojnihcdcdejhi

 

 

Exported with Share Extensions for Google Chrome™ - https://chrome.google.com/webstore/detail/chdafcbnfkfenoeejpaeenpdamhmalhe

 

Thx!

**Comment by alexp-sssup** [comment]
This is most probably a cdn caching issue. Please try again tomorrow, if
the problem is still there please share with us the browser console output.

Il 06/gen/2018 09:23 PM, "johnyradio" <notifications@github.com> ha scritto:

Hello



It didn’t seem to work.

Problem: Your badge showed gray when I loaded page, even tho’ page has
applet.

Then I clicked your “Run applets” button, and got your progress spinner.

Problem: Was still spinning after 10 minutes.



Maybe another extension is conflicting?

Here are my extensions:



Generated: Sat, 06 Jan 2018 20:20:46 GMT

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36



Extensions: 24

- Lazy Tabs: https://chrome.google.com/webstore/detail/
aabgbgciohhaogajcnacpgilhmacdahc

- ShowPassword: https://chrome.google.com/webstore/detail/
bbiclfnbhommljbjcoelobnnnibemabl

- CheerpJ Applet Runner Beta: https://chrome.google.com/webstore/detail/
bbmolahhldcbngedljfadjlognfaaein

- appear.in screen sharing: https://chrome.google.com/webstore/detail/
bodncoafpihbhpfljcaofnebjkaiaiga

- Share Extensions: https://chrome.google.com/webstore/detail/
chdafcbnfkfenoeejpaeenpdamhmalhe

- uBlock Origin: https://chrome.google.com/webstore/detail/
cjpalhdlnbpafiamejdnhcphjbkeiagm

- CSS and Javascript Injection: https://chrome.google.com/webstore/detail/
ckddknfdmcemedlmmebildepcmneakaa

- Tidy Bookmarks Tree Lite: https://chrome.google.com/webstore/detail/
cojofepigcheogdcgockpcaijonnehec

- Undirect: https://chrome.google.com/webstore/detail/
dohbiijnjeiejifbgfdhfknogknkglio

- YouTube Auto HD + FPS: https://chrome.google.com/webstore/detail/
fcphghnknhkimeagdglkljinmpbagone

- AnnoTabe: https://chrome.google.com/webstore/detail/
fdhebnledngmjdkhgamneiapbmjeigee

- Eye Protector: https://chrome.google.com/webstore/detail/
fgadnbmmolnmbkbklpaojbogcopipopl

- Stop Autoplay for Youtube™: https://chrome.google.com/webstore/detail/
figkapeodjhdgnpiamleongcmecfjccb

- Video Speed: https://chrome.google.com/webstore/detail/
fnjmlegmhldjolpmcfjhooibnchlafgg

- Tab Finder - by floverdevel: https://chrome.google.com/webstore/detail/
hfnickpljocfadhinpemeekdeebaenlo

- Speed-Up Browsing: https://chrome.google.com/webstore/detail/
hkhnldpdljhiooeallkmlajnogjghdfb

- Tab Extract: https://chrome.google.com/webstore/detail/
iphchnegaodmijmkdlbhbanjhfphhikp

- Disable Extensions Temporarily: https://chrome.google.com/webstore/detail/
lcfdefmogcogicollfebhgjiiakbjdje

- Zoom Tab: https://chrome.google.com/webstore/detail/
legekacjhcjbkhjnggkbbibckddakkaa

- Audio EQ: https://chrome.google.com/webstore/detail/
lfafdlnjaliaghpjdajmlcnnblkgcefh

- Grabilla Screenshot: https://chrome.google.com/webstore/detail/
mlkejhoeobiibeeeahncjhhonbholbje

- Personal Blocklist (by Google): https://chrome.google.com/webstore/detail/
nolijncfnkgaikbjbdaogikpmpbdcdef

- 1-Click Extension Manager: https://chrome.google.com/webstore/detail/
ohajmcdpjokbdoihfhkpbmlmknejmoec

- Web Cache Viewer: https://chrome.google.com/webstore/detail/
pbkloffickinnlnmefmjmjbacohecpbd



Disabled Extensions: 6

- Move tabs between windows: https://chrome.google.com/webstore/detail/
dcgkknngicjdagcjljfbhgdimlfhafag

- Google Docs Offline: https://chrome.google.com/webstore/detail/
ghbmnnjooekpmoecnnnilnnbdlolhkhi

- BF - Boost Facebook: https://chrome.google.com/webstore/detail/
jaopmidjghipjkgdkhnielilaoodeefj

- Disable autoplay on youtube: https://chrome.google.com/webstore/detail/
mhnjhaekhlafoabhhpakebdpemkddcjd

- Smart Ads Finder: https://chrome.google.com/webstore/detail/
oojeieppkffpbnmlpipfbblophebaplg

- Data Saver: https://chrome.google.com/webstore/detail/
pfmgfdlgomnbgkofeojodiodmgpgmkac



Apps: 2

- Codebender App: https://chrome.google.com/webstore/detail/
magknjdfniglanojbpadmpjlglepnlko

- 3D STL, OBJ Viewer with Drive: https://chrome.google.com/webstore/detail/
pjbghnibbgbmpokpcfoojnihcdcdejhi





Exported with Share Extensions for Google Chrome™ -
https://chrome.google.com/webstore/detail/chdafcbnfkfenoeejpaeenpdamhmalhe



Thx!

**Comment by johnyradio** [comment]
Ok
