### ISSUE TITLE
"Version 10.2 Updated 28 August 2021" does not work with oekaki BBS.

### ISSUE THREAD

**Issue by satopian** [leaningtech/cheerpj-appletrunner#50]
If i use the new version of the Chrome extension "CheerpJ Applet Runner" on the bulletin board using JavaApplet's drawing tool "shi-Painter", 
i will be returned to the previous page from the Java startup screen.
As a result, Java Applet will not start.
For example, if i start "CheerpJ Applet Runner" after to call the paint screen in index.php, 
i will be taken to the top page of the bulletin board from the paint screen.(It will return to the previous screen)
It works when there is an Applet in one HTML,
but it does not work on the bulletin board because it often calls the Java page after pressing the paint button.
However, directly on the Java applet launch screen
`https://cjrtnc.leaningtech.com/2.2/loader.js`
There is no problem if i paste and start.
This is a problem when using the Chrome extension.
Thank you.

**Comment by alexp-sssup** [comment]
Is there a publicly accessible page where we can test this behavior?

Please note that version 10.2 uses a different strategy that we were forced to implement due to changes in Chrome Web Store policies. We have written a long post explaining the work here: https://medium.com/leaningtech/the-bottomless-pit-of-disappointment-a-chrome-extension-tale-21e5cf84da0

**Comment by satopian** [comment]
http://neo.websozai.jp/
Uncheck "NEOを使う" (use html5 version) and start Java Applet.(お絵かきするbutton)
Also, the character code of old Japanese websites is Shift jis. This string seems to cause garbled characters.
Older versions of the extension worked fine.
![0831_00](https://user-images.githubusercontent.com/44894014/131474852-1407f2b4-64e9-4ba8-9c51-33a06f640686.gif)
![0831_02](https://user-images.githubusercontent.com/44894014/131476070-366e5bcf-48b4-4741-a035-6fc1c2785ac1.gif)

**Comment by alexp-sssup** [comment]
We have investigated the problem, it is caused by the applet page being loaded using HTTP POST.

Due to the limitations imposed on us by the Chrome Web Store, CheerpJ Applet Runner cannot anymore inject the script automatically on enabled domains, but need to manually reload the page before injecting the CheerpJ loader.

This does not work on this page since an automatic redirect to index.html happens when CheerpJ Applet Runner tries to reload the page.

We have implemented a new settings to inject the CheerpJ loader without forcing a reload. This will fix this page, but might break other ones, so it cannot be enabled by default.

The new setting will be available with the upcoming version 10.3, which will be available in a few days, due to the review time of the Chrome Store.

When the new version is available you will need to follow these steps

1) Click on the extension icon. The page will automatically reload.
2) Click on the extension icon one more time. The extension popup will show.
3) Click on the "Settings" button.
4) Enable the "Avoid page reloads (for this domain)" checkbox
5) Reload the page and proceed to the applet page.
6) Click the extension icon one more time to start CheerpJ on this page. No reload will happen and the applet will start.

**Comment by alexp-sssup** [comment]
Please try again with the just published CheerpJ Applet Runner version 10.3, make sure to follow the steps described above.

**Comment by alexp-sssup** [comment]
Apologies, due to a packaging issue this problem is not yet fixed. Version 10.4 will be required.

**Comment by alexp-sssup** [comment]
Please try again with the just published CheerpJ Applet Runner version 10.4, make sure to follow the steps described above.
