### ISSUE TITLE
CheerPJ not working anymore on website http://hydrolab.illinois.edu/gw_applets/

### ISSUE THREAD

**Issue by michaelgchen** [leaningtech/cheerpj-appletrunner#51]
Hi there I used CheerPJ to load the Applet's of my University course, Groundwater Applets, since March 2021 and it was working for months, but it suddenly stopped working, I was wondering what could have happened. Does anybody have any ideas?

Thank you so much in advance

**Comment by sere** [comment]
Dear michaelgchen,

The CheerpJ extension was recently updated. Unfortunately, due to restrictions imposed by the google chrome store, the user interface had to change. Now CheerpJ Applet Runner requires to be activated every time you reload a tab, even if you activated it before on that website.

For http://hydrolab.illinois.edu/gw_applets/ this means that you have to click on the CheerpJ Applet Runner icon every time you load a model. If it opens a separate window where the menu bar is missing, try copying the URL in a new, "normal" tab in the browser.
