### ISSUE TITLE
FoilSim applet does not work properly

### ISSUE THREAD

**Issue by Alexey-Akishin** [leaningtech/cheerpj-appletrunner#7]
I have attempted to use it to run FoilSim https://www.grc.nasa.gov/www/k-12/airplane/foil3.html - and at first it looked like it works, but I cannot use dropboxes, when I try to change some value, for example angle-deg, from 0 to 10, nothing happens, even if press Enter. If I attempt to drag slider for angle-deg value, it becomes -19.6 and cannot be changed. I cannot change units from Imperial to Metric.

These issues make the applet unusable, it does not work properly. I would appreciate greatly if somebody looks into this issues.

**Comment by alexp-sssup** [comment]
All the issues you mentioned are known. CheerpJ does currently only partially support AWT components. CheerpJ does fully support all Swing component on the other hand. We plan to fully support AWT components in the future but, since there has been no commercial demand for this feature, we currently do not have a definite timeline for it.

**Comment by alexp-sssup** [comment]
Combo-boxes and sliders are now correctly supported in CheerpJ Applet Runner 3.0

Closing
